class TextUtils {
  static const Set<String> stopWords = {
    'a',
    'about',
    'above',
    'after',
    'again',
    'against',
    'all',
    'am',
    'an',
    'and',
    'any',
    'are',
    'aren\'t',
    'as',
    'at',
    'be',
    'because',
    'been',
    'before',
    'being',
    'below',
    'between',
    'both',
    'but',
    'by',
    'can',
    'cannot',
    'could',
    'couldn\'t',
    'did',
    'didn\'t',
    'do',
    'does',
    'doesn\'t',
    'doing',
    'don\'t',
    'down',
    'during',
    'each',
    'few',
    'for',
    'from',
    'further',
    'had',
    'hadn\'t',
    'has',
    'hasn\'t',
    'have',
    'haven\'t',
    'having',
    'he',
    'he\'d',
    'he\'ll',
    'he\'s',
    'her',
    'here',
    'here\'s',
    'hers',
    'herself',
    'him',
    'himself',
    'his',
    'how',
    'how\'s',
    'i',
    'i\'d',
    'i\'ll',
    'i\'m',
    'i\'ve',
    'if',
    'in',
    'into',
    'is',
    'isn\'t',
    'it',
    'it\'s',
    'its',
    'itself',
    'let\'s',
    'me',
    'more',
    'most',
    'mustn\'t',
    'my',
    'myself',
    'no',
    'nor',
    'not',
    'of',
    'off',
    'on',
    'once',
    'only',
    'or',
    'other',
    'ought',
    'our',
    'ours',
    'ourselves',
    'out',
    'over',
    'own',
    'same',
    'shan\'t',
    'she',
    'she\'d',
    'she\'ll',
    'she\'s',
    'should',
    'shouldn\'t',
    'so',
    'some',
    'such',
    'than',
    'that',
    'that\'s',
    'the',
    'their',
    'theirs',
    'them',
    'themselves',
    'then',
    'there',
    'there\'s',
    'these',
    'they',
    'they\'d',
    'they\'ll',
    'they\'re',
    'they\'ve',
    'this',
    'those',
    'through',
    'to',
    'too',
    'under',
    'until',
    'up',
    'very',
    'was',
    'wasn\'t',
    'we',
    'we\'d',
    'we\'ll',
    'we\'re',
    'we\'ve',
    'were',
    'weren\'t',
    'what',
    'what\'s',
    'when',
    'when\'s',
    'where',
    'where\'s',
    'which',
    'while',
    'who',
    'who\'s',
    'whom',
    'why',
    'why\'s',
    'with',
    'won\'t',
    'would',
    'wouldn\'t',
    'you',
    'you\'d',
    'you\'ll',
    'you\'re',
    'you\'ve',
    'your',
    'yours',
    'yourself',
    'yourselves',
    'will',
    // 'can', // Duplicate removed
    'may',
    'might',
    'must',
    // 'should', // Duplicate removed
    // 'would', // Duplicate removed
    'job',
    'description',
    'requirements',
    'role',
    'responsibilities',
    'opportunity',
    'work',
    'working',
    'team',
    'experience',
    'years',
    'plus',
    'preferred',
    'qualification',
    'qualifications',
    'degree',
    'bachelor',
    'master',
    'equivalent',
    'field',
    'related',
    'strong',
    'knowledge',
    'ability',
    'skills',
    'including',
    'within',
    'environment',
    'looking',
    'candidate',
    'ensure',
    'support',
    'create',
    'develop',
    'design',
    'implement',
    'maintain',
    'excellent',
    'communication',
    'good',
    // 'must', // Duplicate
    // 'have', // Duplicate
    'proficient',
    'proficiency',
    'understanding',
    'familiarity',
    'familiar',
    'using',
    'used',
    'various',
    'best',
    'practices',
    'concepts',
    'principles',
    'proven',
    'track',
    'record',
    'hands-on',
    'demonstrated',
    // 'ability', // Duplicate
  };

  static Set<String> tokenize(String text) {
    if (text.isEmpty) return {};

    // 1. Lowercase
    String normalized = text.toLowerCase();

    // 2. Remove punctuation (allow alphanumeric and spaces)
    // Replacing any non-alphanumeric character with a space to avoid merging words
    normalized = normalized.replaceAll(RegExp(r'[^a-z0-9\s]'), ' ');

    // 3. Split by whitespace
    List<String> tokens = normalized.split(RegExp(r'\s+'));

    // 4. Filter stop words & short words
    Set<String> validTokens = {};
    for (String token in tokens) {
      if (token.length > 2 && !stopWords.contains(token)) {
        validTokens.add(token);
      }
    }

    return validTokens;
  }
}
